apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  destinations:
  - namespace: apps
    server: https://kubernetes.default.svc
  sourceRepos:
  - git@github.com:nwoodII/argocd-example-apps.git
