apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
spec:
  destinations:
  - namespace: team-burnham
    server: https://kubernetes.default.svc
  sourceRepos:
  - git@github.com:nwoodII/aws-app-mesh-examples.git