apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aws-xray-kubernetes
  namespace: argocd
spec:
  destinations:
  - namespace: aws-xray-kubernetes
    server: https://kubernetes.default.svc
  sourceRepos:
  - git@github.com:aws-samples/aws-xray-kubernetes.git
