apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: apps
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.apps.apps.repoURL }}
    targetRevision: {{ .Values.spec.apps.apps.targetRevision }}
    path: {{ .Values.spec.apps.apps.path }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true