spec:
  destination:
    server: https://kubernetes.default.svc
  apps:
    blueGreen:
      repoURL: https://github.com/nwoodII/argocd-example-apps.git
      targetRevision: HEAD
      path: blue-green 
    apps:
      repoURL: https://github.com/nwoodII/argocd-example-apps.git
      targetRevision: HEAD
      path: apps    
    awsXrayKubernetes:
      repoURL: https://github.com/aws-samples/aws-xray-kubernetes.git
      targetRevision: HEAD
      path: demo-app       
    eksBlueprintsWorkloads:
      repoURL: https://github.com/nwoodII/eks-blueprints-workloads.git
      targetRevision: HEAD
      path: envs/dev    
    ecsdemoFrontend:
      repoURL: git@github.com:aws-containers/ecsdemo-frontend.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-frontend
    ecsdemoNodejs:
      repoURL: git@github.com:aws-containers/ecsdemo-nodejs.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-nodejs
    ecsdemoCrystal:
      repoURL: git@github.com:aws-containers/ecsdemo-crystal.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-crystal      