spec:
  destination:
    server: https://kubernetes.default.svc
  apps:
    blueGreen:
      repoURL: https://github.com/nwoodII/argocd-example-apps.git
      targetRevision: HEAD
      path: blue-green 
    apps:
      repoURL: https://github.com/nwoodII/argocd-example-apps.git
      targetRevision: HEAD
      path: apps    
    # awsXrayKubernetes:
    #   repoURL: https://github.com/aws-samples/aws-xray-kubernetes.git
    #   targetRevision: HEAD
    #   path: demo-app       
    eksBlueprintsWorkloads:
      repoURL: https://github.com/nwoodII/eks-blueprints-workloads.git
      targetRevision: HEAD
      path: envs/dev  
    awsAppMeshExamples:
      repoURL: https://github.com/aws/aws-app-mesh-examples.git
      targetRevision: HEAD
      path: examples/apps/djapp/1_base_application        
    awsAppMeshExamplesTwo:
      repoURL: https://github.com/aws/aws-app-mesh-examples.git
      targetRevision: HEAD
      path: examples/apps/djapp/2_base_application        