spec:
  destination:
    server: https://kubernetes.default.svc
  apps:
    blueGreen:
      repoURL: https://github.com/nwoodII/argocd-example-apps.git
      targetRevision: HEAD
      path: blue-green 