spec:
  destination:
    server: https://kubernetes.default.svc
  apps:
    blueGreen:
      repoURL: git@github.com:nwoodII/argocd-example-apps.git
      targetRevision: main
      path: blue-green     